swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: Show the last twenty transactions of user
      description: API for get last transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/ApiTransactionsResponse'
        '400':
          description: Invalid Fields
        '404':
          description: Transactions not found
        '500':
          description: Internal Server Error
  /user/transaction:
        post:
            security:
                - Bearer: []
            tags:
                - Transaction module
            summary: Add a transaction
            description: API for adding a transaction
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
                - in: body
                  name: body
                  description: Data needed for create a new transaction
                  required: true
                  schema:
                      $ref: "#/definitions/addTransaction"
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction added successfully
                    schema:
                        $ref: "#/definitions/ApiTransactionResponse"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error
  /user/transaction/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: Return a transaction
      description: API for get a transaction and show it
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: id of transaction
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiTransactionResponse'
        '400':
          description: Invalid Fields
        '404':
          description: Id unknown
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: Edit a transaction
      description: API for updating a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: id of transaction
          required: true
          type: string
        - in: body
          name: body
          description: Edit transaction
          required: true
          schema:
            $ref: '#/definitions/editTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiTransactionResponse'
        '400':
          description: Invalid Fields
        '404':
          description: transaction unknown
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: Delete a transaction
      description: API for delete a transaction with id
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: Id of transaction
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction deleted successfully
        "400":
          description: Invalid Fields
        "404":
          description: Transaction unknown
        "500":
          description: Internal Server Error
  
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  ApiTransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          transactionList1:
            type: object
            description: transaction
            properties:
              id:
                type: string
                description: id of transaction
                example: 9648523558
              content:
                type: string
                description: transaction content
                example: Argent Bank Checking (x8349)
              sum:
                type: string
                description: transaction sum
                example: $2,082.79
              balance:
                type: string
                description: transaction balance
                example: Available Balance
          transactionList2:
            type: object
            description: transaction
            properties:
              id:
                type: string
                description: id of transaction
                example: 5648527558
              content:
                type: string
                description: transaction content
                example: Argent Bank Savings (x6712)
              sum:
                type: string
                description: transaction sum
                example: $10,928.42
              balance:
                type: string
                description: transaction balance
                example: Available Balance
          transactionList3:
            type: object
            description: transaction
            properties:
              id:
                type: string
                description: id of transaction
                example: 5648523558
              content:
                type: string
                description: transaction content
                example: Argent Bank Credit Card (x8349)
              sum:
                type: string
                description: transaction sum
                example: $184.30
              balance:
                type: string
                description: transaction balance
                example: Current Balance
  ApiTransactionResponse:
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description: id of transaction
          content:
            type: string
            description: transaction content
          sum:
            type: string
            description: transaction sum
          balance:
            type: string
            description: transaction balance
  addTransaction:
    properties:
      id:
        type: string
        description: id of transaction
      content:
        type: string
        description: transaction content
      sum:
        type: string
        description: transaction sum
      balance:
        type: string
        description: transaction balance
  editTransaction:
    type: object
    properties:
      content:
        type: string
        description: transaction content